"""initial schema: tables, slots, bookings, booking_status_logs

Revision ID: c772d11c9e8f
Revises: 
Create Date: 2026-09-10 19:49:52.643263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c772d11c9e8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_tables_capacity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_slots_duration_positive'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'date', 'start_time', name='uq_slot_table_date_time')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=120), nullable=False),
    sa.Column('guest_phone', sa.String(length=30), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled', 'no-show')", name='ck_bookings_status_valid'),
    sa.CheckConstraint('party_size > 0', name='ck_bookings_party_size_positive'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('uq_active_booking_per_slot', ['slot_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'confirmed')"), postgresql_where=sa.text("status IN ('pending', 'confirmed')"))

    op.create_table('booking_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('pending', 'confirmed', 'cancelled', 'no-show')", name='ck_booking_status_logs_from_status_valid'),
    sa.CheckConstraint("to_status IN ('pending', 'confirmed', 'cancelled', 'no-show')", name='ck_booking_status_logs_to_status_valid'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_status_logs')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('uq_active_booking_per_slot', sqlite_where=sa.text("status IN ('pending', 'confirmed')"), postgresql_where=sa.text("status IN ('pending', 'confirmed')"))

    op.drop_table('bookings')
    op.drop_table('slots')
    op.drop_table('tables')
    # ### end Alembic commands ###
